### ISSUE TITLE
Report: only shows checks for the current check type

### ISSUE THREAD

**Issue by loganlebanoff** [WycliffeAssociates/8woc#318]

**Comment by EvanWiederspan** [comment]
I just tried it on develop and this doesn't appear to be happening. I switched from lexical to example check, made a new report and data from the lexical check still showed up. By design, the report will only show information from a check if that check gives us data, so if the example check and tN check have not been initialized, it is very likely that their data will not show on reports (and I think it should be this way). Was something different happening for you?

**Comment by loganlebanoff** [comment]
Ok, you're right. This was an issue, but then I think you fixed it shortly after.
